# This workflow will build a MuleSoft project and deploy to CloudHub

name: Cloudhub deployment with Maven [main]

on:
  push:
    branches: [ main ]

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Deploy to Exchange
      run: mvn clean deploy -s settings.xml -DskipTests
    
    - name: Deploy to Runtime
      run: mvn clean deploy -DmuleDeploy -s -DskipTests 
